apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx-ingress-controller
  values:
  controller:
    ingressClassResource:
      name: private
      enabled: true
      default: true
    ingressClass: private

