apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ogc-loki
spec:
  releaseName: ogc-loki
  chart:
    spec:
      chart: loki-simple-scalable
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
